# Generated by Django 3.1.2 on 2020-12-06 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20201205_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='database.comment'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
