# Generated by Django 3.1.2 on 2020-12-07 00:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20201205_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='likes',
            field=models.ManyToManyField(related_name='item_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
