# Generated by Django 3.1.2 on 2020-12-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20201206_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='authentication/static/authentication'),
        ),
    ]
