# Generated by Django 3.1.2 on 2020-12-08 02:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='item_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
