# Generated by Django 3.1.2 on 2020-12-02 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemSale', '0002_auto_20201201_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userid',
        ),
    ]
